
name: build


# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  actions: write
  checks: read
  contents: read
  deployments: read
  issues: none
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: none
  statuses: read


on:
  workflow_dispatch:
    inputs:
      #devfast:
        #type: boolean
        #default: true
      #skimfast:
        #type: boolean
        #default: true
      runnerName:
        required: false
        default: ubuntu-latest-m
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-latest-m
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    ##- cron: '5 1 * * 6'
    ##- cron: '5 1 * * 2,4'
    ##- cron: '5 1 * * 2'
    - cron: '5 1 * * 5'
    #- cron: '5 1 10 * *'

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true





# https://github.com/ncipollo/release-action
# https://github.com/softprops/action-gh-release
# https://svrooij.io/2021/08/17/github-actions-secret-file/
jobs:
  build_guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
            tag_name: build-${{ github.run_id }}-${{ github.run_attempt }} #(required) tag name to delete 
            github_token: ${{ secrets.GITHUB_TOKEN }}
            delete_release: true #(optional) default: true 
  build_nix:
    needs: [build_guard]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'recursive'
      - name: _getMinimal_cloud
        shell: bash
        timeout-minutes: 120
        run: |
          ./ubiquitous_bash.sh _getMinimal_cloud
      - name: _getMinimal-build_extendedInterface
        shell: bash
        timeout-minutes: 120
        run: |
          ./ubiquitous_bash.sh _getMinimal-build_extendedInterface
      - name: build-fetch
        shell: bash
        timeout-minutes: 120
        run: |
          mkdir -p ../extendedInterface-accessories/integrations/ubcp
          curl -L -o ../extendedInterface-accessories/integrations/ubcp/package_ubcp-core.7z  $(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/mirage335-colossus/ubiquitous_bash/releases" | jq -r ".[] | select(.name == \"internal\") | .assets[] | select(.name == \"package_ubcp-core.7z\") | .browser_download_url" | sort -n -r | head -n1)  
          ./ubiquitous_bash.sh _build_extendedInterface-fetch
      - name: build-build
        shell: bash
        timeout-minutes: 120
        run: |
          rm -f ../extendedInterface-accessories/integrations/ubcp/package_ubcp-core.7z
          ./ubiquitous_bash.sh _build_extendedInterface-build
      - name: release!
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_id }}-${{ github.run_attempt }}
          name: build
          files: |
            ../extIface.exe







